api/urls.py
from django.urls import path

from api.views import (
    add_goods,
    billing_callback,
    buy_subscription,
    categories_chart_data,
    provider_chart_data
)

urlpatterns = [
    path('goods/add', add_goods),
    path('billing/callback', billing_callback),
    path('subscription/buy', buy_subscription, name="buy-subscription"),
    path('chart/providers', provider_chart_data),
    path('chart/categories', categories_chart_data),
]

kwork/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from data_panel import views as panel_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('billing/', panel_views.billing, name="billing"),
    path('api/', include('api.urls')),
    path('accounts/', include('allauth.urls')),
    path('', panel_views.ItemListView.as_view(), name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data_panel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    valid_until = models.DateTimeField(verbose_name="Подписка действует до")
    is_trial = models.BooleanField(verbose_name="Пробная версия", default=True)

    def __str__(self):
        return f"{self.user.username} subscription"

    def is_active(self):
        return self.valid_until > timezone.now()

    class Meta:
        verbose_name = "Подписка на сервис"
        verbose_name_plural = "Подписки на сервис"


class PaymentsInfo(models.Model):
    user = models.ForeignKey(User, null=True, verbose_name="Пользователь", on_delete=models.SET_NULL)
    status = models.CharField(max_length=20, verbose_name="Статус платежа")
    amount = models.IntegerField(verbose_name="Сумма")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"[{self.id}] {self.user.username}'s payment "

    class Meta:
        verbose_name = "Платёж"
        verbose_name_plural = "Платежи"


class Provider(models.Model):
    name = models.CharField(max_length=300, unique=True, null=True, blank=True, verbose_name="Поставщик")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Поставщик"
        verbose_name_plural = "Поставщики"


class Category(models.Model):
    name = models.CharField(max_length=300, unique=True, null=True, blank=True, verbose_name="Категория")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Brand(models.Model):
    name = models.CharField(max_length=300, unique=True, null=True, blank=True, verbose_name="Бренд")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Бренд"
        verbose_name_plural = "Бренды"


class ItemUrl(models.Model):
    url = models.CharField(max_length=300, null=True, blank=True, verbose_name="Ссылка на страницу товара")

    def __str__(self):
        return f"{self.url}"

    class Meta:
        verbose_name = "Ссылка на товар"
        verbose_name_plural = "Ссылки на товар"


class Item(models.Model):
    provider = models.ForeignKey(Provider, null=True, blank=True, verbose_name="Поставщик", on_delete=models.SET_NULL)
    name = models.CharField(max_length=300, null=True, blank=True, verbose_name="Название товара")
    image_url = models.CharField(max_length=300, null=True, blank=True, verbose_name="Ссылка на изображение")
    url = models.ForeignKey(ItemUrl, verbose_name="Ссылка на страницу товара", on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, null=True, blank=True, verbose_name="Бренд", on_delete=models.SET_NULL)
    vendor_code = models.IntegerField(null=True, blank=True, verbose_name="Артикул")
    rating = models.IntegerField(null=True, blank=True, verbose_name="Рейтинг")
    reviews = models.IntegerField(null=True, blank=True, verbose_name="Количество отзывов")
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name="Цена без скидки")
    price_with_discount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True,
                                              verbose_name="Цена со скидкой")
    quantity = models.IntegerField(null=True, blank=True, verbose_name="Доступно")
    categories = models.ManyToManyField(Category, blank=True, verbose_name="Категории")
    quantity_of_purchased = models.IntegerField(null=True, blank=True, verbose_name="Количество покупок")
    revenue = models.DecimalField(max_digits=35, decimal_places=2, null=True, blank=True, verbose_name="Выручка")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return f"{self.name} {self.brand} [{self.vendor_code}]"

data_panel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

data_panel/views.py
import re

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.http import QueryDict
from django.shortcuts import render
from django_filters.views import FilterView

from .filters import ItemFilter
from .helpers import get_item_query
from .mixins import SubscriptionRequiredMixin
from .models import Item


@login_required
def billing(request):
    return render(request, 'billing.html')


class ItemListView(LoginRequiredMixin, SubscriptionRequiredMixin, FilterView):
    template_name = 'item_list.html'
    paginate_by = 25
    model = Item
    filterset_class = ItemFilter

    queryset = get_item_query()

    def get_context_data(self, **kwargs):
        table_headers = [
            {"id": "name", "name": "Товар"},
            {"id": "brand", "name": "Бренд"},
            {"id": "provider", "name": "Поставщик"},
            {"id": "rating", "name": "Рейтинг"},
            {"id": "reviews", "name": "Отзывы"},
            {"id": "price_with_discount", "name": "Цена"},
            {"id": "quantity", "name": "Доступно"},
            {"id": "categories", "name": "Категории"},
            {"id": "quantity_of_purchased", "name": "Куплено"},
            {"id": "revenue", "name": "Выручка"}
        ]

        ordering = self.request.GET.get('order_by', None)

        for header in table_headers:
            query = QueryDict(self.request.GET.urlencode(), mutable=True)

            if ordering == f"-{header['id']}":
                query["order_by"] = f"{header['id']}"
            elif ordering != header['id']:
                query["order_by"] = f"-{header['id']}"
            else:
                query["order_by"] = ""

            query['page'] = 1
            header['url'] = f"?{query.urlencode()}"

        if ordering:
            match_obj = re.match(r'-?(.+)', ordering)
            order_field = match_obj.groups()[0]
            order_field_index = next((index for (index, d) in enumerate(table_headers) if d["id"] == order_field), None)
            table_headers[order_field_index]["active"] = True
            table_headers[order_field_index]["down"] = ordering != order_field

        context = super().get_context_data(**kwargs)
        context['table_headers'] = table_headers
        return context

    def get_ordering(self):
        fields = [
            "id", "provider", "name", "brand", "vendor_code",
            "rating", "reviews", "price", "price_with_discount",
            "quantity", "categories", "quantity_of_purchased", "revenue"
        ]
        ordering = self.request.GET.get('order_by', 'id')

        match_obj = re.match(r'-?(.+)', ordering)

        if match_obj and (match_obj.groups()[0] in fields):
            field = match_obj.groups()[0]

            if field == ordering:
                return [F(field).asc(nulls_first=True)]
            else:
                return [F(field).desc(nulls_last=True)]

        return 'id'

data_panel/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Data viewer</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.0/dist/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.24.0/axios.min.js"
            integrity="sha512-u9akINsQsAkG9xjc1cnGF4zw5TFDwkxuc9vUp5dltDWYCSmyd0meygbvgXrlc/z7/o4a19Fb5V0OUE58J7dcyw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>


</head>
<body style="background-color: #EDEEF0;">

{% block content %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

data_panel/templates/billing.html
{% extends "base.html" %}
{% load tz %}
{% block content %}
    <div class="container mt-4 pb-4">
        <div class="card">
            <div class="card-body">
                <h2>Состояние подписки</h2>
                <div class="border-top pt-3">
                    {% if user.subscription.is_active %}
                        {% if user.subscription.is_trial %}
                            Активирована пробная версия подписки до
                        {% else %}
                            Ваша подписка будет активна до
                        {% endif %}
                        {{ ' ' }}
                        <strong>{{ user.subscription.valid_until|timezone:"Europe/Moscow" }} МСК</strong>
                    {% else %}
                        <strong class="text-danger">Срок вашей подписки истёк</strong>
                    {% endif %}
                </div>
                {% if not user.subscription.is_active or user.subscription.is_trial %}
                    <a class="btn btn-info px-4 mt-2" href="{% url 'buy-subscription' %}">Купить подписку</a>
                {% endif %}
                <a class="btn btn-warning px-4 mt-2" href="{% url 'index' %}">К товарам</a>
                <a class="btn btn-primary px-4 mt-2" href="{% url 'account_logout' %}">Выйти</a>
            </div>
        </div>
        {% if user.paymentsinfo_set.all %}
            <div class="card mt-3">
                <div class="card-body">
                    <h2 class="mb-3">История платежей</h2>
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Дата</th>
                                <th scope="col">Сумма</th>
                                <th scope="col">Статус</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for payment in user.paymentsinfo_set.all|dictsortreversed:"created_at" %}
                                <tr>
                                    <td>{{ payment.created_at|timezone:"Europe/Moscow" }} МСК</td>
                                    <th class="text-danger">-{{ payment.amount }}</th>
                                    <th>{{ payment.status }}</th>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

data_panel/templates/item_list.html
{% extends "base.html" %}
{% load bootstrap_pagination %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="container-lg p-4">
        {# header #}
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <span>Вы вошли под логином: <strong>{{ user.username }}</strong></span>
                    <div class="d-flex">
                        <a class="btn btn-info px-4" href="{% url 'billing' %}">Подписка</a>
                        <a class="ml-2 btn btn-primary px-4" href="{% url 'account_logout' %}">Выйти</a>
                    </div>
                </div>
            </div>
        </div>

        {# Filters #}
        <div class="card mt-4">
            <div class="card-body">
                <h4>Фильтры</h4>
                <hr/>
                <form method="get">
                    <label for="id_price">Цена без скидки:</label>
                    <div class="input-group mb-3" id="id_price">
                        <div class="input-group-prepend"><span class="input-group-text">От</span></div>
                        <input
                                type="number"
                                name="price__gt"
                                step="any"
                                class="numberinput form-control" id="id_price__gt"
                                value="{{ request.GET.price__gt }}"
                        >
                        <div class="input-group-prepend"><span class="input-group-text">До</span></div>
                        <input
                                type="number"
                                name="price__lt"
                                step="any"
                                class="numberinput form-control" id="id_price__lt"
                                value="{{ request.GET.price__lt }}"
                        >
                    </div>

                    <label for="id_price_with_discount">Цена со скидкой:</label>
                    <div class="input-group mb-3" id="id_price_with_discount">
                        <div class="input-group-prepend"><span class="input-group-text">От</span></div>
                        <input
                                type="number"
                                name="price_with_discount__gt"
                                step="any"
                                class="numberinput form-control" id="id_price_with_discount__gt"
                                value="{{ request.GET.price_with_discount__gt }}"
                        >
                        <div class="input-group-prepend"><span class="input-group-text">До</span></div>
                        <input
                                type="number"
                                name="price_with_discount__lt"
                                step="any"
                                class="numberinput form-control" id="id_price_with_discount__lt"
                                value="{{ request.GET.price_with_discount__lt }}"
                        >
                    </div>

                    <label for="id_rating">Рейтинг:</label>
                    <div class="input-group mb-3" id="id_rating">
                        <div class="input-group-prepend"><span class="input-group-text">От</span></div>
                        <input
                                type="number"
                                name="rating__gt"
                                step="any"
                                class="numberinput form-control" id="id_rating__gt"
                                value="{{ request.GET.rating__gt }}"
                        >
                        <div class="input-group-prepend"><span class="input-group-text">До</span></div>
                        <input
                                type="number"
                                name="rating__lt"
                                step="any"
                                class="numberinput form-control" id="id_rating__lt"
                                value="{{ request.GET.rating__lt }}"
                        >
                    </div>

                    <label for="id_reviews">Количество отзывов:</label>
                    <div class="input-group mb-3" id="id_reviews">
                        <div class="input-group-prepend"><span class="input-group-text">От</span></div>
                        <input
                                type="number"
                                name="reviews__gt"
                                step="any"
                                class="numberinput form-control" id="id_reviews__gt"
                                value="{{ request.GET.reviews__gt }}"
                        >
                        <div class="input-group-prepend"><span class="input-group-text">До</span></div>
                        <input
                                type="number"
                                name="reviews__lt"
                                step="any"
                                class="numberinput form-control" id="id_reviews__lt"
                                value="{{ request.GET.reviews__lt }}"
                        >
                    </div>

                    <label for="id_revenue">Выручка:</label>
                    <div class="input-group mb-3" id="id_revenue">
                        <div class="input-group-prepend"><span class="input-group-text">От</span></div>
                        <input
                                type="number"
                                name="revenue__gt"
                                step="any"
                                class="numberinput form-control" id="id_revenue__gt"
                                value="{{ request.GET.revenue__gt }}"
                        >
                        <div class="input-group-prepend"><span class="input-group-text">До</span></div>
                        <input
                                type="number"
                                name="revenue__lt"
                                step="any"
                                class="numberinput form-control" id="id_revenue__lt"
                                value="{{ request.GET.revenue__lt }}"
                        >
                    </div>

                    <div class="d-flex justify-content-end">
                        <input type="submit" class="btn btn-primary" value="Применить"/>
                        <a href="/" class="btn btn-secondary ml-2">Сбросить</a>
                    </div>
                </form>
            </div>
        </div>

        {# Charts #}
        <div class="card mt-4">
            <div class="card-body">
                <div class="d-flex justify-content-around" style="height: 300px;">
                    <div style="width: 100%">
                        <canvas id="chart1"></canvas>
                    </div>
                    <div style="width: 100%">
                        <canvas id="chart2"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="card mt-4">
            <div class="card-body">
                <div class="d-flex justify-content-around" style="height: 300px;">
                    <div style="width: 100%">
                        <canvas id="chart3"></canvas>
                    </div>
                    <div style="width: 100%">
                        <canvas id="chart4"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'charts.js' %}"></script>
        <script>
            axios.get('/api/chart/categories').then(response => {
                createChart('chart1', 'Продажи', response.data.chart1)
                createChart('chart2', 'Выручка', response.data.chart2)
            });
            axios.get('/api/chart/providers').then(response => {
                createChart('chart3', 'Продажи', response.data.chart1)
                createChart('chart4', 'Выручка', response.data.chart2)
            });
        </script>

        {# Table #}
        <div class="card mt-4">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        {% for theader in table_headers %}
                            <th scope="col" class="border-0 bg-light p-0">
                                <div class="d-flex align-items-center justify-content-center">
                                    {% if theader.active %}
                                        <a class="btn btn-primary w-100" href="{{ theader.url }}">
                                            <span class="font-weight-bold">{{ theader.name }}</span>
                                            {% if theader.down %}
                                                <small class="ml-1 mb-1">
                                                    <i class="fa fa-chevron-down"></i>
                                                </small>
                                            {% else %}
                                                <small class="ml-1 mb-1">
                                                    <i class="fa fa-chevron-up"></i>
                                                </small>
                                            {% endif %}
                                        </a>
                                    {% else %}
                                        <a class="btn btn-light w-100 {# text-uppercase #}" href="{{ theader.url }}">
                                            <span class="font-weight-bold">{{ theader.name }}</span>
                                        </a>
                                    {% endif %}
                                </div>
                            </th>
                        {% endfor %}
                    </thead>
                    <tbody>
                    {% for item in object_list %}
                        <tr>
                            <th scope="row" class="border-0 p-0">
                                <div class="p-2 d-flex align-items-center">
                                    <img src="{{ item.image_url }}" alt="{{ item.name }}"
                                         class="img-fluid rounded shadow-sm" style="max-width: 75px;"/>
                                    <div class="ml-3 d-inline-block">
                                <span class="mb-0">
                                    <a href="{{ item.url }}"
                                       class="text-dark d-inline-block align-middle">
                                        {{ item.name|default_if_none:"—" }}
                                    </a>
                                </span>
                                        <span class="text-muted font-weight-normal font-italic d-block">
                                            Артикул:{{ ' ' }}{{ item.vendor_code|default_if_none:"—" }}
                                        </span>
                                    </div>
                                </div>
                            </th>
                            <td class="border-0 align-middle text-center">
                                {{ item.brand|default_if_none:"—" }}
                            </td>
                            <td class="border-0 align-middle text-center">
                                {{ item.provider|default_if_none:"—" }}
                            </td>
                            <td class="border-0 align-middle text-center">
                                <i class="fa fa-star text-warning"></i>
                                {{ item.rating|default_if_none:"0" }}
                            </td>
                            <td class="border-0 align-middle text-center">
                                {% if item.reviews %}{{ item.reviews }} шт.{% else %}—{% endif %}
                            </td>
                            <td class="border-0 align-middle text-center">
                                <span>{{ item.price_with_discount|default_if_none:"—" }}</span>
                                {% if item.price %}
                                    <span class="text-danger"><small><i><s>{{ item.price }}</s></i></small></span>
                                {% endif %}
                            </td>

                            <td class="border-0 align-middle text-center">
                                {% if item.quantity %}{{ item.quantity }} шт.{% else %}—{% endif %}
                            </td>

                            <td class="border-0 align-middle text-center">
                                {% if item.categories.all %}{{ item.categories.all|join:"/" }}{% else %}—{% endif %}
                            </td>

                            <td class="border-0 align-middle text-center">
                                {% if item.quantity_of_purchased %}{{ item.quantity_of_purchased }} шт.{% else %}
                                    —{% endif %}
                            </td>

                            <td class="border-0 align-middle text-center">
                                {{ item.revenue|default_if_none:"—" }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {# Pagination #}
        {% if page_obj.has_other_pages %}
            <div class="mt-4">
                {% bootstrap_paginate page_obj range=10 extra_pagination_classes="justify-content-center" %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

data_panel/templates/sign-in.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-4 pb-4">
        <div class="card">
            <div class="card-body">
                <div class="content-section">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Вход</legend>
                            {{ form|crispy }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Войти</button>
                        </div>
                    </form>
                    <div class="border-top pt-3">
                        <small class="text-muted">
                            Нет аккаунта? <a class="ml-2" href="{% url 'sign-up' %}">Зарегистрируйтесь</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

data_panel/templates/sign-out.html
{% extends "base.html" %}
{% block content %}
    <div class="container mt-4 pb-4">
        <div class="card">
            <div class="card-body">
                <h2>Вы успешно вышли</h2>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        <a href="{% url 'sign-in' %}">Войти снова</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

data_panel/templates/sign-up.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-4 pb-4">
        <div class="card">
            <div class="card-body">
                <div class="content-section">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Регистрация</legend>
                            {{ form|crispy }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Зарегистрироваться</button>
                        </div>
                    </form>
                    <div class="border-top pt-3">
                        <small class="text-muted">
                            Уже есть аккаунт? <a class="ml-2" href="{% url 'sign-in' %}">Войдите</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}